"""Primeira migration

Revision ID: e9e869d995bc
Revises: 
Create Date: 2022-08-17 19:37:19.201230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e869d995bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crm', sa.String(length=10), nullable=False),
    sa.Column('crmUf', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=127), nullable=True),
    sa.Column('schedule', sa.DateTime(), nullable=True),
    sa.Column('idDoctor', sa.Integer(), nullable=True),
    sa.Column('idPatient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDoctor'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['idPatient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_appointment')
    op.drop_table('patient')
    op.drop_table('doctor')
    # ### end Alembic commands ###
